"""add risk_score risk_level combination_alerts to reports

Revision ID: 4921a2caecd7
Revises: 92f5e04860ac
Create Date: 2026-05-21 16:17:10.187677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4921a2caecd7'
down_revision: Union[str, Sequence[str], None] = '92f5e04860ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('combination_alerts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'combination_alerts')
    op.drop_column('reports', 'risk_level')
    op.drop_column('reports', 'risk_score')
    # ### end Alembic commands ###
