"""add medical scores and organ summary

Revision ID: 747882d7d095
Revises: 4921a2caecd7
Create Date: 2026-06-01 18:30:49.345104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747882d7d095'
down_revision: Union[str, Sequence[str], None] = '4921a2caecd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('mews_score', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('qsofa_score', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('organ_system_summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'organ_system_summary')
    op.drop_column('reports', 'qsofa_score')
    op.drop_column('reports', 'mews_score')
    # ### end Alembic commands ###
